config/routes.rb
Prabhakarweb::Application.routes.draw do
  resources :feedbacks

  resources :articles

root :to => 'feedbacks#home'

get 'contactus' => 'feedbacks#contactus'
get 'home' => 'feedbacks#home'
get 'aboutus' => 'feedbacks#aboutus'
get 'feedback' => 'feedbacks#new'
get 'services' => 'feedbacks#services'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  validates :name, presence: true
  validates :mobile, presence: true, numericality: true, length: { is: 10 }
  validates :email, email: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:name, :mobile, :email, :comments)
    end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]
  layout 'myapplication'
  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  def home
    render action: 'home', layout: 'application'
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(feedback_params)

    if @feedback.save
      redirect_to root_path, notice: 'Feedback was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /feedbacks/1
  # PATCH/PUT /feedbacks/1.json
  def update
    if @feedback.update(feedback_params)
      redirect_to @feedback, notice: 'Feedback was successfully updated.'
      head :no_content
    else
      render action: 'edit'
      render json: @feedback.errors, status: :unprocessable_entity
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback.destroy
    redirect_to feedbacks_url
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_feedback
    @feedback = Feedback.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def feedback_params
    params.require(:feedback).permit(:name, :mobile, :email, :remarks)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/articles/_form.html.erb
<%= form_for @article, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :mobile, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :mobile, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :comments, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :comments, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary'%>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                articles_path, :class => 'btn' %>
  </div>
<% end %>

app/views/articles/aboutus.html.erb
<<!DOCTYPE html>
<html>
<head>
<style>
p.padding
{
padding-top:80px;
padding-bottom:25px;
padding-right:50px;
padding-left:50px;
}
</style>
</head>

<p>
<p class="padding">
<div class="row">
    <div class="span5">
		<%= image_tag("prabhakar photo.png", :size => "200x200", :alt => "prabhakar photo") %>
	</div>
    
    <div class="span7">
		<p>
PB&Co. was established by CS Prabhakar Battula and is a Corporate Legal Services Firm. PB&Co. is registered as a Practicing Company Secretaries firm with the Institute of Company Secretaries of India (ICSI). Our legal and advisory services play a vital role in implementing robust control mechanisms to facilitate compliance of the challenging and ever changing regulations of the country.</br> </br>
PB&Co. has immense knowledge and experience in dealing with matters relating to Company Law, Securities Laws, inbound and outbound Investment, Legal Due Diligence, Transaction documents, Joint Ventures, Foreign Collaborations, Technology Transfers, Mergers and Acquisitions, Listings and Capital Market Transactions.</br> </br>
PB&Co.’s key offerings also include setting up compliances, approvals from all the government departments including approvals from the Registrar of Companies, Ministry of Corporate Affairs, Foreign Investment Promotion Board (FIPB), Secretariat of Industrial Approvals (SIA), Reserve Bank of India (RBI), Director General of Foreign Trade (DGFT), Software Technology Parks of India (STPI), approvals for establishment of 100% Export Oriented Units (EOU), approvals for establishment of units in the Special Economic Zones (SEZ), Foreign Exchange Regulations, Foreign Direct Investment (FDI) in Real Estate, Retail, Trading, Non-banking finance companies etc.</br> </br>
Headquartered in Hyderabad and has been on the forefront of the corporate sector advising, guiding, servicing and representing many companies’ in India and across the globe. PB&Co. has had a formidable track record and is distinguished by its people, its clients and timely deliverables.</br> </br>
We have experience of over 12 years in handling complex legal issues touching on almost all aspects of Indian Corporate  law.</p></p>
	</div>
</div>
</p>

</html>

app/views/articles/contactus.html.erb
<<!DOCTYPE html>
<html>
<head>
<style>
p.padding
{
padding-top:45px;
padding-bottom:25px;
padding-right:50px;
padding-left:50px;
}
</style>
</head>

<h1>
<p class="padding">
<div class="row">
    <div class="span4">

<p>CS Prabhakar Battula</br> <br/> 
H.No:2-3-486/1, Road No.7<br/>
Lalitha Nagar, Sai Nagar<br/>
Near Alakapuri Cross Roads<br/>
Hyderabad - 500 068<br/> 
<br/>  
mobile: +91-9676076226<br/>
email: prabhakar.battula@gmail.com<br/>
</p>

</h1>

</html>

app/views/articles/edit.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/home.html.erb
<<!DOCTYPE html>
<html>
<head>
<style>
p.padding
{
padding-top:45px;
padding-bottom:25px;
padding-right:50px;
padding-left:50px;
}
</style>
</head>

<p>
<p class="padding">
<div class="row">
    <div class="span9">

<p>Our Mission is to deliver outstanding client services; to provide fulfilling careers and professional satisfaction for our people; and to achieve financial success so that we can reward ourselves and grow.</br> </br>
On time delivery is one of our firm’s policy. This is achieved through efficient and ethical work environment. Our services to the clients are provided both onsite as well as offsite. We offer customized services either on assignment to assignment basis or on a retainer basis based on the requirement of the client.  We also provide opinions on various matters of interpretations of the law.</br> </br>
We firmly believe that the success of the firm is dependent on the success of the clients buinsess and this is achieved by understanding our clients’ objectives, by developing a strong grasp of their business and their industry, and by building trusted relationships with their people.</br> </br>
We respect the confidentiality and privacy of our clients, our colleagues and others with whom we are professionally involved.
</p> 




</p>

</html>

app/views/articles/index.html.erb
<%- model_class = Article -%>

<body> 
  {padding:60px} 
</body>

<div class="page-header">

  <h1><%=t '.name', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-hovered">
  <thead>

  <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to article.id, article_path(article) %></td>
        <td><%= article.name %></td>
        <td><%= article.email_id %></td>
        <td><%=l article.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_article_path(article), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      article_path(article),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
</p>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_article_path,
            :class => 'btn btn-primary' %>

app/views/articles/new.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @article.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mobile) %>:</strong></dt>
  <dd><%= @article.mobile %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @article.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:comments) %>:</strong></dt>
  <dd><%= @article.comments %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              articles_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_article_path(@article), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              article_path(@article),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/feedbacks/_form.html.erb
<%= form_for(@feedback) do |f| %>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% @feedback.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.text_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :remarks %><br>
    <%= f.text_area :remarks %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feedbacks/aboutus.html.erb
<<!DOCTYPE html>
<html>
<head>
<style>
p.padding
{
padding-top:80px;
padding-bottom:25px;
padding-right:50px;
padding-left:50px;
}
</style>
</head>

<p>
<p class="padding">
<div class="row">
    <div class="span5">
		<%= image_tag("prabhakar photo.png", :size => "200x200", :alt => "prabhakar photo") %>
	</div>
    
    <div class="span7">
		<p align="justify">
PB&Co. was established by CS Prabhakar Battula and is a Corporate Legal Services Firm. PB&Co. is registered as a Practicing Company Secretaries firm with the Institute of Company Secretaries of India (ICSI). Our legal and advisory services play a vital role in implementing robust control mechanisms to facilitate compliance of the challenging and ever changing regulations of the country.</br> </br>
PB&Co. has immense knowledge and experience in dealing with matters relating to Company Law, Securities Laws, inbound and outbound Investment, Legal Due Diligence, Transaction documents, Joint Ventures, Foreign Collaborations, Technology Transfers, Mergers and Acquisitions, Listings and Capital Market Transactions.</br> </br>
PB&Co.’s key offerings also include setting up compliances, approvals from all the government departments including approvals from the Registrar of Companies, Ministry of Corporate Affairs, Foreign Investment Promotion Board (FIPB), Secretariat of Industrial Approvals (SIA), Reserve Bank of India (RBI), Director General of Foreign Trade (DGFT), Software Technology Parks of India (STPI), approvals for establishment of 100% Export Oriented Units (EOU), approvals for establishment of units in the Special Economic Zones (SEZ), Foreign Exchange Regulations, Foreign Direct Investment (FDI) in Real Estate, Retail, Trading, Non-banking finance companies etc.</br> </br>
Headquartered in Hyderabad and has been on the forefront of the corporate sector advising, guiding, servicing and representing many companies’ in India and across the globe. PB&Co. has had a formidable track record and is distinguished by its people, its clients and timely deliverables.</br> </br>
We have experience of over 12 years in handling complex legal issues touching on almost all aspects of Indian Corporate  law.</p></p>
	</div>
</div>
</p>

</html>

app/views/feedbacks/contactus.html.erb
<<!DOCTYPE html>
<html>
<head>
<style>
p.padding
{
padding-top:60px;
padding-bottom:25px;
padding-right:50px;
padding-left:50px;
}
</style>
</head>

<p1>
<p class="padding">
<div class="row">
    <div class="span4">

<p>CS Prabhakar Battula</br> <br/> 
H.No:2-3-486/1, Road No.7<br/>
Lalitha Nagar, Sai Nagar<br/>
Near Alakapuri Cross Roads<br/>
Hyderabad - 500 068<br/> 
<br/>  
mobile: +91-9676076226<br/>
email: prabhakar.battula@gmail.com<br/>
</p>

</p1>

</html>

app/views/feedbacks/edit.html.erb
<h1>Editing feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/home.html.erb
<<!DOCTYPE html>
<html>
<head>
<style>
p.padding
{
padding-top:45px;
padding-bottom:25px;
padding-right:50px;
padding-left:50px;
}
</style>
</head>

<p>
<p class="padding">
<div class="row">
    <div class="span9">

<p align="justify">Our Mission is to deliver outstanding client services; to provide fulfilling careers and professional satisfaction for our people; and to achieve financial success so that we can reward ourselves and grow.</br> </br>
On time delivery is one of our firm’s policy. This is achieved through efficient and ethical work environment. Our services to the clients are provided both onsite as well as offsite. We offer customized services either on assignment to assignment basis or on a retainer basis based on the requirement of the client.  We also provide opinions on various matters of interpretations of the law.</br> </br>
We firmly believe that the success of the firm is dependent on the success of the clients buinsess and this is achieved by understanding our clients’ objectives, by developing a strong grasp of their business and their industry, and by building trusted relationships with their people.</br> </br>
We respect the confidentiality and privacy of our clients, our colleagues and others with whom we are professionally involved.
</p> 




</p>

</html>

app/views/feedbacks/index.html.erb
<h1>Listing feedbacks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mobile</th>
      <th>Email</th>
      <th>Remarks</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= feedback.name %></td>
        <td><%= feedback.mobile %></td>
        <td><%= feedback.email %></td>
        <td><%= feedback.remarks %></td>
        <td><%= link_to 'Show', feedback %></td>
        <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
        <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feedback', new_feedback_path %>

app/views/feedbacks/myhome.html.erb
<p>
<p> my home</p>
  <p class="padding">
    <% if flash[:notice] %>
      <div class="row">
        <div class="span9">
          <h1> <%= flash[:notice] %></h1>
        </div>
      </div>
    <% end  %>
    <div class="row">
      <div class="span9">
        <p align="justify">Our Mission is to deliver outstanding client services; to provide fulfilling careers and professional satisfaction for our people; and to achieve financial success so that we can reward ourselves and grow.</br> </br>
      On time delivery is one of our firm’s policy. This is achieved through efficient and ethical work environment. Our services to the clients are provided both onsite as well as offsite. We offer customized services either on assignment to assignment basis or on a retainer basis based on the requirement of the client.  We also provide opinions on various matters of interpretations of the law.</br> </br>
  We firmly believe that the success of the firm is dependent on the success of the clients buinsess and this is achieved by understanding our clients’ objectives, by developing a strong grasp of their business and their industry, and by building trusted relationships with their people.</br> </br>
We respect the confidentiality and privacy of our clients, our colleagues and others with whom we are professionally involved.
</p>
<p> my home</p>

</div>
</div>

app/views/feedbacks/new.html.erb
<head>
<style>
p.padding
{
padding-top:45px;
padding-bottom:25px;
padding-right:50px;
padding-left:50px;
}
</style>
</head>

<p>
<%- model_class = Feedback -%>
<div class="page-header">
  <p class="padding"> </p>
  <h6><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h6>
</div>
<%= render :partial => 'form' %>
</p>

app/views/feedbacks/services.html.erb
<<!DOCTYPE html>
<html>
<head>
<style>
p.padding
{
padding-top:45px;
padding-bottom:25px;
padding-right:50px;
padding-left:50px;
}
</style>
</head>

<h1>
<p class="padding">
<div class="row">
    <div class="span7">
<p>-> Dealing Under Corporate Laws, Labour Laws And Economic Laws</p>
<p>-> Certifications and Audits</p>
<p>-> Advisory Services</p>
<p>-> Management Services</p>
<p>-> Compliances Under Company Law</p>
<p>-> Certifications to Bankers & Financial Institutions</p>
<p>-> Other Services
 
</h1>
     

</html>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @feedback.name %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @feedback.mobile %>
</p>

<p>
  <strong>Email:</strong>
  <%= @feedback.email %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @feedback.remarks %>
</p>

<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Prabhakar Battula & Co." %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          
          <%= image_tag("pbc logo.jpg", :size => "200x200", :alt => "PBC logo") %>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Home", "/home"  %></li>
              <li><%= link_to "About Us", "/aboutus"  %></li>
              <li><%= link_to "Services", "/services"  %></li>
              <li><%= link_to "Feedback", "/feedback"  %></li>
              <li><%= link_to "Contact Us", "/contactus"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
 

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          

      <footer>
               <p>______________________________________</p>
        <p>&copy; copyright Prabhakar Battula & Co. 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/myapplication.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Prabhakar Battula & Co." %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>

          <%= image_tag("pbc logo.jpg", :size => "200x200", :alt => "PBC logo") %>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Home", "/home"  %></li>
              <li><%= link_to "About Us", "/aboutus"  %></li>
              <li><%= link_to "Services", "/services"  %></li>
              <li><%= link_to "Feedback", "/feedback"  %></li>
              <li><%= link_to "Contact Us", "/contactus"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>


    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
      <footer>
               <p>______________________________________</p>
        <p>&copy; copyright Prabhakar Battula & Co. 2014</p>
      </footer>
    </div> <!-- /container -->
  </body>
</html>